### ISSUE TITLE
UBIFTException: Cannot find specified UBI Volume

### ISSUE THREAD

**Issue by JavitoLope** [matthias-deu/ubift#1]
1. Download ubi image
http://chip.jfpossibilities.com/chip/images/stable/pocketchip/126/chip-400000-4000-500.ubi.sparse

2. Use simg2img to convert sparse image to raw image.

3. Check (page size: 0x4000, ubifs at 0x8000)
00000000: 5542 4923 0100 0000 0000 0000 0000 0000  UBI#............
00004000: 5542 4921 0101 0005 7fff efff 0000 0000  UBI!............
00008000: 0000 071d 0000 0001 0000 0000 0100 0006  ................
00008010: 726f 6f74 6673 0000 0000 0000 0000 0000  rootfs..........

3. List files
$ python3 ./ubift.py fls ../chip-400000-4000-500.ubi -o 0 -n data
Traceback (most recent call last):
  File "/mnt/ubift-master/./ubift.py", line 7, in <module>
    b.run()
  File "/mnt/ubift-master/ubift/cli/__init__.py", line 190, in run
    args.func(args)
  File "/mnt/ubift-master/ubift/cli/__init__.py", line 750, in fls
    ubi_vol = self._initialize_ubi_volume(ubi, args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ubift-master/ubift/cli/__init__.py", line 306, in _initialize_ubi_volume
    raise exception.UBIFTException(
ubift.exception.UBIFTException: [-] Cannot find specified UBI Volume. Either the volname or volindex is invalid.

**Comment by matthias-deu** [comment]
Hey, I looked at the image and it seems that it has a lot of irregularities, such as incorrect magic values and unexpected structures within its UBIFS formatting.

For instance if i read the superblock node manually at 16384 in the file created from simg2img i get:

```
UBIFS_SB_NODE(ch=UBIFS_CH(magic=101718065, crc=2915628769, sqnum=485288, len=4096, node_type=6, group_type=0, padding=[0, 0]), padding=[0, 0], key_hash=0, key_fmt=0, flags=0, min_io_size=16384, leb_size=2064384, leb_cnt=300, max_leb_cnt=4
096, max_bud_bytes=8388608, log_lebs=4, lpt_lebs=2, orph_lebs=1, jhead_cnt=1, fanout=8, lsave_cnt=256, fmt_version=4, default_compr=1, padding1=[0, 0], rp_uid=0, rp_gid=0, rp_size=0, time_gran=1000000000, uuid=[0, 54, 57, 214, 130, 87, 79
, 225, 143, 123, 94, 45, 144, 110, 148, 52], ro_compat_version=0,
```

But its mentioned **leb_size=2064384** would not make sense as there would be a EC_HEADER (UBI#) expected after every 2064384 bytes. That and some other things cause UBIFT to fail, i can maybe try to fix it so its more lenient but it might take a while.
